"""Mikoshi Curiosity — domain-agnostic exploration engine."""

__version__ = "0.10.0"

from mikoshi_curiosity.space import State, StateSpace
from mikoshi_curiosity.engine import CuriosityEngine
from mikoshi_curiosity.memory import ExplorationMemory, MemoryEntry
from mikoshi_curiosity.prediction import PredictionModel
from mikoshi_curiosity.results import Discovery, ExplorationResult, ExplorationStats
from mikoshi_curiosity.archive import ResearchArchive
from mikoshi_curiosity.cognitive import (
    CognitiveRecord,
    CognitiveRuntime,
    CognitiveStore,
    CycleResult,
    ExecutivePlanner,
    ProposedAction,
)
from mikoshi_curiosity.lean_repair import LeanRepairAdapter
from mikoshi_curiosity.llm import (
    AnthropicProvider,
    CallableTextProvider,
    CodexCLIProvider,
    LLMConjectureGenerator,
    LLMLeanRepairer,
    OllamaProvider,
    OpenAIProvider,
    TextProvider,
)
from mikoshi_curiosity.model_finder import (
    FiniteModelFinder,
    FiniteModelProofAdapter,
    FiniteModelSpec,
    ModelSearchResult,
)
from mikoshi_curiosity.debt import (
    DebtExperiment,
    class_count,
    duplicate_fanout,
    fanout_is_information_neutral,
    gate_refinement_bound,
    refine_signatures,
    run_debt_experiment,
    terminal_rows_distinguished,
    unresolved_debt,
)
from mikoshi_curiosity.sat_queries import (
    IndexSATQuery,
    SATOrientationExperiment,
    SplitCNFSize,
    bit_cnf,
    brute_cnf_satisfiable,
    cnf_satisfiable,
    correctness_forces_orientation,
    index_answer,
    index_query_cnf,
    orientation_is_injective,
    query_family,
    run_sat_orientation_experiment,
    sat_orientation,
    split_index_cnf,
    split_index_cnf_correct,
    split_index_cnf_parts,
    split_index_cnf_size,
)
from mikoshi_curiosity.amplification import (
    AmplificationAudit,
    one_hot,
    run_amplification_audit,
    shared_index_dag,
    shared_index_gate_count,
)
from mikoshi_curiosity.tableau import (
    TableauRecoveryAudit,
    counter_step,
    counter_trace,
    ripple_transition_gate_bound,
    run_tableau_recovery_audit,
)
from mikoshi_curiosity.solver_capture import (
    CaptureAudit,
    audit_hankel_capture,
    capture_doubles,
    hankel_load,
    kronecker,
    rational_rank,
)
from mikoshi_curiosity.research import (
    AssumptionChallengeMutator,
    AssumptionAuditCritic,
    CallableConjectureGenerator,
    CallableProofAdapter,
    CallableResearchCritic,
    CandidateEvaluation,
    CircularityCritic,
    CommandProofAdapter,
    CompletenessCritic,
    Concept,
    ConceptGraph,
    Conjecture,
    ConjectureGenerator,
    ConjectureMutator,
    Critique,
    FuzzyAnalogyMutator,
    HashEmbedder,
    KnownFailureCritic,
    ProofAdapter,
    ProofResult,
    ResearchCritic,
    ResearchEvaluator,
    ResearchStateSpace,
    TemplateGenerator,
)
from mikoshi_curiosity.scoring import (
    novelty_score,
    surprise_score,
    diversity_score,
    serendipity_score,
    diminishing_returns,
    balanced_score,
)

__all__ = [
    "State",
    "StateSpace",
    "CuriosityEngine",
    "ExplorationMemory",
    "MemoryEntry",
    "PredictionModel",
    "Discovery",
    "ExplorationResult",
    "ExplorationStats",
    "ResearchArchive",
    "CognitiveRecord",
    "CognitiveRuntime",
    "CognitiveStore",
    "CycleResult",
    "ExecutivePlanner",
    "ProposedAction",
    "LeanRepairAdapter",
    "AnthropicProvider",
    "CallableTextProvider",
    "CodexCLIProvider",
    "LLMConjectureGenerator",
    "LLMLeanRepairer",
    "OllamaProvider",
    "OpenAIProvider",
    "TextProvider",
    "FiniteModelFinder",
    "FiniteModelProofAdapter",
    "FiniteModelSpec",
    "ModelSearchResult",
    "DebtExperiment",
    "class_count",
    "duplicate_fanout",
    "fanout_is_information_neutral",
    "gate_refinement_bound",
    "refine_signatures",
    "run_debt_experiment",
    "terminal_rows_distinguished",
    "unresolved_debt",
    "IndexSATQuery",
    "SATOrientationExperiment",
    "SplitCNFSize",
    "bit_cnf",
    "brute_cnf_satisfiable",
    "cnf_satisfiable",
    "correctness_forces_orientation",
    "index_answer",
    "index_query_cnf",
    "orientation_is_injective",
    "query_family",
    "run_sat_orientation_experiment",
    "sat_orientation",
    "split_index_cnf",
    "split_index_cnf_correct",
    "split_index_cnf_parts",
    "split_index_cnf_size",
    "AmplificationAudit",
    "one_hot",
    "run_amplification_audit",
    "shared_index_dag",
    "shared_index_gate_count",
    "TableauRecoveryAudit",
    "counter_step",
    "counter_trace",
    "ripple_transition_gate_bound",
    "run_tableau_recovery_audit",
    "CaptureAudit",
    "audit_hankel_capture",
    "capture_doubles",
    "hankel_load",
    "kronecker",
    "rational_rank",
    "AssumptionChallengeMutator",
    "AssumptionAuditCritic",
    "CallableConjectureGenerator",
    "CallableProofAdapter",
    "CallableResearchCritic",
    "CandidateEvaluation",
    "CircularityCritic",
    "CommandProofAdapter",
    "CompletenessCritic",
    "Concept",
    "ConceptGraph",
    "Conjecture",
    "ConjectureGenerator",
    "ConjectureMutator",
    "Critique",
    "FuzzyAnalogyMutator",
    "HashEmbedder",
    "KnownFailureCritic",
    "ProofAdapter",
    "ProofResult",
    "ResearchCritic",
    "ResearchEvaluator",
    "ResearchStateSpace",
    "TemplateGenerator",
    "novelty_score",
    "surprise_score",
    "diversity_score",
    "serendipity_score",
    "diminishing_returns",
    "balanced_score",
]
